"""add learner profile fields"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '93df464500fc'
down_revision: Union[str, Sequence[str], None] = 'c7a4b1d2e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learners', sa.Column('skills', sa.JSON(), nullable=False))
    op.add_column('learners', sa.Column('verified_skills', sa.JSON(), nullable=False))
    op.alter_column('learners', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learners', 'education',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('learners', 'verified_skills_json')
    op.drop_column('learners', 'skills_json')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learners', sa.Column('skills_json', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('learners', sa.Column('verified_skills_json', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('learners', 'education',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('learners', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('learners', 'verified_skills')
    op.drop_column('learners', 'skills')
    # ### end Alembic commands ###
