"""create backend tables"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'b05e26de1aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('employer_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('required_skills_json', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_requirements_employer_id'), 'employer_requirements', ['employer_id'], unique=False)
    op.create_table('employers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_account_id'), 'employers', ['account_id'], unique=True)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_job_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_external_job_id'), 'job_postings', ['external_job_id'], unique=True)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('learners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('current_role', sa.String(length=120), nullable=True),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('preferred_region', sa.String(length=120), nullable=True),
    sa.Column('preferred_language', sa.String(length=80), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('profile_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_account_id'), 'learners', ['account_id'], unique=True)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_skills_json', sa.Text(), nullable=False),
    sa.Column('missing_skills_json', sa.Text(), nullable=False),
    sa.Column('verified_skills_json', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_employer_id'), 'match_results', ['employer_id'], unique=False)
    op.create_index(op.f('ix_match_results_learner_id'), 'match_results', ['learner_id'], unique=False)
    op.create_table('micro_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_step_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('rubric_json', sa.Text(), nullable=False),
    sa.Column('test_cases_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_micro_projects_roadmap_step_id'), 'micro_projects', ['roadmap_step_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_learner_id'), 'roadmaps', ['learner_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_learner_id'), 'submissions', ['learner_id'], unique=False)
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sandbox_passed', sa.Boolean(), nullable=False),
    sa.Column('judge_feedback', sa.Text(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('unlocks_next', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_learner_id'), 'verification_results', ['learner_id'], unique=False)
    op.create_index(op.f('ix_verification_results_project_id'), 'verification_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_verification_results_submission_id'), 'verification_results', ['submission_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_submission_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_project_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_learner_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_submissions_project_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_learner_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_roadmaps_learner_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_micro_projects_roadmap_step_id'), table_name='micro_projects')
    op.drop_table('micro_projects')
    op.drop_index(op.f('ix_match_results_learner_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_employer_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_learners_account_id'), table_name='learners')
    op.drop_table('learners')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_external_job_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_employers_account_id'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_employer_requirements_employer_id'), table_name='employer_requirements')
    op.drop_table('employer_requirements')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
