"""align learner profile storage"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = 'f20e2847b7b0'
down_revision: Union[str, Sequence[str], None] = '93df464500fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learners', sa.Column('skills_json', sa.Text(), nullable=False))
    op.add_column('learners', sa.Column('verified_skills_json', sa.Text(), nullable=False))
    op.alter_column('learners', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('learners', 'skills')
    op.drop_column('learners', 'verified_skills')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learners', sa.Column('verified_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('learners', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('learners', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('learners', 'verified_skills_json')
    op.drop_column('learners', 'skills_json')
    # ### end Alembic commands ###
